sigdotcom/mstacm.org

- api/src/resources/Event/entity.ts
- api/src/resources/Event/index.ts
- api/src/resources/Event/input.ts
- api/src/resources/Event/resolver.ts
- api/src/resources/Sig/entity.ts
- api/src/resources/User/entity.ts
Adds in the Database Schema, and related GraphQL endpoints for the Event resource, to be used on the homepage and other apps.
> Add Events to DB/GraphQL

- api/.docker/letsencrypt/nginx/ldap.conf
- api/.docker/letsencrypt/nginx/nginx.conf
- api/.docker/letsencrypt/nginx/proxy.conf
- api/.docker/letsencrypt/nginx/site-confs/default
- api/.docker/letsencrypt/nginx/ssl.conf
- api/.gitignore
- api/docker-compose.production.yml
- api/docker-compose.yml
- api/tsconfig.release.json
- deploy.sh
Make deployment configuration much more robust with automatic service restarts, automatic SSL Nginx proxy with letsencrypt certifications/auto refresh, and backup restore documentation
> Increase robustness of production deployment

- api/ormconfig.js
- api/package.json
- api/src/main.ts
> Fix build directory not being consistent with tsconfig

- apps/admin-web/package.json
- apps/admin-web/src/App.tsx
- apps/admin-web/src/components/pages/ToolList.tsx
- apps/admin-web/src/components/pages/tools/Events/EventForm.tsx
- apps/admin-web/src/config.ts
- apps/admin-web/src/index.tsx
- apps/admin-web/src/static/css/App.css
- apps/admin-web/src/utils/apollo.ts
- apps/admin-web/src/utils/react-auth0-wrapper.tsx
- apps/admin-web/tslint.json
- apps/admin-web/yarn.lock
This PR adds login to the admin dashboard. When connecting to the admin dashboard, you will be redirected to login if you are not already logged in, otherwise you will see the tools.
> Add authentication to Admin Dashboard

- api/.docker/web.env.default
Update the ormconfig.js to adhere to the tsconfig build src changes.
Fix `web.env.default` variable AUTH0_DOMAIN having extra padding around the `=`.
> Fix production build consistency

- api/docker-compose.override.yml
- api/src/lib/products.ts
- api/src/main.ts
- api/src/migrations/1567049233839-initial_data.ts
- api/src/migrations/1568237426157-statementDescriptor.ts
- api/src/resources/Product/entity.ts
- api/src/resources/Purchase/input.ts
- api/src/resources/Transaction/resolver.ts
- api/yarn.lock
- apps/web/src/components/CheckoutForm.tsx
- apps/web/src/config.ts
- apps/web/src/generated/graphql.tsx
> Add generic single product payment mutation

- apps/web/src/screens/HomePage/sections/Nav.tsx
Closes:  #93 
**Before:**
**After:**
> Issue was z-index.

- api/src/resources/Event/resolver.ts
> Add event scopes for 'add', 'update', and 'delete'

- api/src/middleware/auth.ts
> Fix profile pictures to be set properly on sign-up

- apps/web/src/screens/HomePage/sections/Events/index.tsx
> Fix no events message from 'takea look' -> 'take a look'

- api/src/migrations/1570415211795-permission_management.ts
- api/src/resources/Group/entity.ts
- api/src/resources/Permission/resolver.ts
- api/src/resources/RedemptionCode/resolver.ts
- api/src/resources/Resume/resolver.ts
- api/src/resources/Transaction/resolver.ts
- api/src/resources/User/entity.ts
- api/src/resources/User/resolver.ts
> Add permission management for Users with permisisons/groups

- apps/api/.docker/web.env.default
- apps/api/package.json
- apps/api/src/config.ts
- apps/api/src/lib/files.ts
- apps/api/src/resources/Resume/resolver.ts
- apps/api/yarn.lock
- apps/docker-compose.yml
> Use digitalocean spaces instead of azure for file uploads

- apps/admin-web/package.json
- apps/admin-web/src/components/pages/tools/Events/EventForm.tsx
- apps/admin-web/src/components/pages/tools/Events/helpers.ts
- apps/admin-web/src/utils/apollo.ts
- apps/api/src/resources/Event/input.ts
- apps/api/src/resources/Event/resolver.ts
- apps/profile-web/src/generated/graphql.tsx
Adds the resolvers necessary to upload fliers for events, and to Digital Ocean Spaces.
Adds the form components in the Admin dashboard to upload.
> Add Flier Upload to Events

- apps/api/src/resources/RedemptionCode/resolver.ts
Recent changes to redemptionCodes allow for groups, permissions,
and products. If there is no product, it sets the transaction to be
null. The redeemRedemptionCode resolver was not updated to take this
potentially null transaction into account and would throw an error.
> Fix redemptionCodes without product failing to redeem

- apps/web/src/screens/HomePage/sections/Footer.tsx
The ACM-W link was incorrect, this PR changes the link to the new, correct link: https://women.mstacm.org/
> Updated ACM-W link in footer

- apps/web/src/screens/HomePage/sections/Sponsors.tsx
As we have a new sponsor, DigitalOcean, I have added their sponsor card to the website.
> Add digitalocean sponsor card

- apps/api/src/config.ts
> Update api to throw error on missing config in production

- apps/web/src/screens/HomePage/sections/Nav.tsx
- apps/web/src/screens/HomePage/sections/Options.tsx
- apps/web/src/screens/HomePage/sections/ProfileOptions.tsx
> finished adding the profile dropdown

- .github/workflows/test_and_deploy.yml
- deploy/main.tf
> Update terraform to .13 and remove depricated terraform-github-actions

- apps/resume-portal/package.json
- apps/resume-portal/src/components/ResumeCard/ResumeCard.tsx
- apps/resume-portal/src/generated/graphql.tsx
- apps/resume-portal/src/index.css
- yarn.lock
> Large Modal Resume View

- apps/web/src/screens/HomePage/sections/Events/Event.tsx
- apps/web/src/screens/HomePage/sections/Events/index.tsx
- apps/web/src/screens/HomePage/sections/Membership/index.tsx
A few small things needed to be done for a long time:
- Resolves #297 
- Resolves #50 
- Padding was inconsistent due to hr being wrong length
> Update some homepage inconsistencies

- apps/admin-web/src/generated/graphql.tsx
- apps/api/yarn.lock
- apps/profile-web/src/generated/graphql.tsx
- apps/resume-portal/src/generated/graphql.tsx
- apps/resume-portal/src/index.css
- apps/web/src/generated/graphql.tsx
- yarn.lock
> Update all packages to latest version

- apps/web/src/screens/HomePage/sections/Footer.tsx
- apps/web/src/screens/HomePage/sections/SIGs/index.tsx
Due to the ACM Security link being changed by their team, the link is now out of date
> Update ACM Security link in Communities section

- apps/web/package.json
- apps/web/src/components/CheckoutForm.tsx
- apps/web/src/components/ModalWrapper.tsx
- apps/web/src/components/PaymentInformation.tsx
- apps/web/src/components/PrimaryButton.tsx
- apps/web/src/components/ReviewInformation.tsx
- apps/web/src/generated/graphql.tsx
- apps/web/src/screens/HomePage/sections/Membership/index.tsx
- apps/web/src/static/css/App.css
- yarn.lock
> Membership Payment Form Redesign

- apps/web/src/screens/HomePage/sections/Footer.tsx
> Updated copyright

- apps/web/src/screens/HomePage/sections/SIGs/index.tsx
> update security email

- apps/web/src/screens/HomePage/sections/SIGs/index.tsx
fixes https://github.com/sigdotcom/mstacm.org/issues/366
> General and Grad Additions to Homepage

- apps/resume-portal/src/components/ResumeCard/ResumeCard.tsx
> Click to Expand is now centered on card

- apps/resume-portal/README.md
> Nick fuller24 patch 1

- apps/web/src/screens/HomePage/sections/Footer.tsx
> feat: refactor the copyright year to date function

- apps/web/src/screens/HomePage/index.tsx
- apps/web/src/screens/HomePage/sections/Events/index.tsx
> Remove Membership

- apps/profile-web/src/App.tsx
Year is now automatically updated
> Year will now be automatically updated

- apps/web/src/screens/HomePage/sections/Events/Event.tsx
- apps/web/src/screens/HomePage/sections/Events/index.tsx
- apps/web/src/screens/HomePage/sections/SIGs/index.tsx
> Removed ACM Game and renamed ACM Arcade to ACM Game

- apps/web/src/screens/HomePage/sections/Nav.tsx
> Membership removed from navbar
